# Generated by Django 2.1.5 on 2019-04-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=26)),
                ('email', models.EmailField(max_length=50)),
                ('sendType', models.CharField(choices=[('register', 'register'), ('forget', 'forget'), ('request', 'request')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email link code',
            },
        ),
    ]
