# Generated by Django 2.1.7 on 2019-04-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phys_incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('incident_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('pulse_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('incident_type', models.CharField(max_length=200)),
                ('recording', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phys_measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('skinny_fat', models.FloatField()),
                ('bp_low', models.IntegerField()),
                ('bp_high', models.IntegerField()),
                ('pr_low', models.IntegerField()),
                ('pr_high', models.IntegerField()),
                ('rr_low', models.IntegerField()),
                ('rr_high', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phys_params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('coef_bp', models.FloatField()),
                ('coef_pr', models.FloatField()),
                ('coef_rr', models.FloatField()),
                ('bias_logit', models.FloatField()),
                ('ar', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wandering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('caregiver_id', models.IntegerField()),
                ('isWandering', models.BooleanField()),
                ('alerted', models.BooleanField()),
            ],
        ),
    ]
