# Generated by Django 2.2 on 2019-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep_trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('date', models.DateField()),
                ('hours_slept', models.FloatField()),
                ('hours_deep_sleep', models.FloatField()),
                ('hours_light_sleep', models.FloatField()),
                ('hours_in_bed', models.FloatField()),
                ('num_wake_up', models.IntegerField()),
                ('num_get_out_of_bed', models.IntegerField()),
                ('num_go_to_bathroom', models.IntegerField()),
            ],
        ),
    ]
