# Generated by Django 2.2 on 2019-04-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_auto_20190416_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('date', models.DateField()),
                ('num_hallucinations', models.IntegerField(blank=True, null=True)),
                ('num_ltm_lapse', models.IntegerField(blank=True, null=True)),
                ('num_stm_lapse', models.IntegerField(blank=True, null=True)),
                ('num_injury', models.IntegerField(blank=True, null=True)),
                ('num_wandering', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
