# Generated by Django 2.2 on 2019-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_incident_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_trend',
            name='hours_deep_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_trend',
            name='hours_in_bed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_trend',
            name='hours_light_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_trend',
            name='hours_slept',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_trend',
            name='num_get_out_of_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_trend',
            name='num_go_to_bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_trend',
            name='num_wake_up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
