# Generated by Django 2.1.7 on 2019-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_id', models.IntegerField(default=0)),
                ('scaled_rating1', models.IntegerField(default=0)),
                ('scaled_rating2', models.IntegerField(default=0)),
                ('test_results', models.TextField(blank=True)),
            ],
        ),
    ]
