# Generated by Django 2.1.7 on 2019-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='wt_caregiver_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wt_patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safezone',
            name='wt_safezone_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
