# Generated by Django 2.1.7 on 2019-04-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wt', '0002_auto_20190415_0351'),
        ('wt', '0002_auto_20190415_0447'),
    ]

    operations = [
    ]
