# Generated by Django 2.2 on 2019-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('doctor', models.IntegerField()),
                ('medication', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='caregiver_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
