# Generated by Django 2.1.7 on 2019-04-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='data',
            field=models.CharField(max_length=5000),
        ),
    ]
