# Generated by Django 2.2 on 2019-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0003_auto_20190420_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(max_length=200)),
                ('patient_id', models.IntegerField()),
                ('sensor_id', models.UUIDField()),
            ],
        ),
    ]
