# Generated by Django 2.1.7 on 2019-04-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('incident_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('pulse_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('incident_type', models.CharField(max_length=200)),
                ('recording', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('doctor', models.IntegerField()),
                ('medication', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('test_score', models.IntegerField()),
                ('num_injuries', models.IntegerField()),
                ('num_falls', models.IntegerField()),
                ('weight', models.FloatField()),
                ('body_fat_percentage', models.FloatField()),
            ],
        ),
    ]
