# Generated by Django 2.2 on 2019-04-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
